project:
  type: website
  output-dir: docs

website:
  title: "TFS SPORT CLUB"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: history.qmd
        text: "History"
      - href: photos.html
        text: "Photos"      
      - href: events.html
        text: "Events"
      - href: contact.html
        text: "Contacts"
        
format:
  html:
    theme: sandstone
    mainfont: arial
    fontsize: 1.5em
    fontcolor: "#1D3605"
    linkcolor: "#ff33f0"
    monofont: courier new
    css: styles.css
    toc: true



